---
benchmark_config:
  generic:
    benchmark: mongodb
    cpus: 0
    transparent_hugepages: never
  redis:
    operation_count: 10
    record_count: 10
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - scheduler_core
