---
benchmark_config:
  generic:
    benchmark: memcached
    cpus: 0
    transparent_hugepages: never
  memcached:
    thread_count: 4
    operation_count: 100
    record_count: 100
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - scheduler_core
