---
benchmark_config:
  generic:
    benchmark: redis
    cpus: 0
    transparent_hugepages: never
  redis:
    operation_count: 100
    record_count: 100
    read_proportion: 0
    update_proportion: 0
    insert_proportion: 0.50
    rmw_proportion: 0
    scan_proportion: 0
    delete_proportion: 0.50
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - compound
