---
benchmark_config:
  generic:
    benchmark: redis
    cpus: 0
    transparent_hugepages: never
  redis:
    operation_count: 100
    record_count: 100
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - compound
