---
benchmark_config:
  generic:
    benchmark: terasort
    cpus: 0
    transparent_hugepages: never
  terasort:
    hadoop_version: "3.2.4"
    num_records: 100
    input_dir: "terasort-input"
    output_dir: "terasort-output"
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - scheduler_core
