---
benchmark_config:
  generic:
    benchmark: xsbench
    cpus: 0
    transparent_hugepages: never
  xsbench:
    threads: 4
    grid_points: 11303
    lookups: 1500
    implementation: "openmp-threading"
    problem_size: "small"
    mode: "history"
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - scheduler_core
